---
- hosts: all
  vars:
    ansible_host_key_checking: false
  gather_facts: yes
  become: yes
  
  tasks:
  
  - name: install debian core packages
    apt:
      name:
        - sudo
        - ntp
        - snmp
        - rsyslog
        - htop
        - bpytop
      update_cache: yes
