---
- hosts: all
  vars:
    ansible_host_key_checking: false
  gather_facts: yes
  become: yes

  tasks:
    - name: Import Wazuh GPG key
      ansible.builtin.apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        keyring: /usr/share/keyrings/wazuh.gpg
        state: present
      register: wazuh_key

    - name: Set permissions on Wazuh GPG key
      ansible.builtin.file:
        path: /usr/share/keyrings/wazuh.gpg
        mode: '0644'
        owner: root
        group: root
      when: wazuh_key is changed

    - name: Add Wazuh repository to sources list
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
        filename: wazuh
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Wazuh Agent
      ansible.builtin.apt:
        name: wazuh-agent
        state: present

    - name: replace MANAGER_IP in ossec.conf
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>MANAGER_IP</address>'
        replace: '<address>NEUE MANAGER IP</address>'

    - name: Stop Wazuh Agent
      ansible.builtin.systemd:
        name: wazuh-agent
        state: stopped

    - name: Start Wazuh Agent
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started

    - name: Disable Wazuh repository after installation to not accidentially install faulty version
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/wazuh.list
        regexp: '^deb'
        line: '#deb'
        state: present

    - name: Update apt cache after disabling repository
      ansible.builtin.apt:
        update_cache: yes
