---
- hosts: all
  vars:
    ansible_host_key_checking: false
  gather_facts: yes
  become: yes
  
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install ca-certificates, curl, gnupg
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and install Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Set read permissions for docker.gpg
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: 'a+r'

    - name: Add Docker repository to sources.list.d
      shell: |
        echo \
          "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
