---
- hosts: all
  vars:
    ansible_host_key_checking: false
  gather_facts: yes
  become: yes

  tasks:
    - name: Ensure Wazuh repository is correctly configured
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/wazuh.list
        state: absent  # Löscht die alte Datei, um sicherzustellen, dass es keine Fehler gibt
        
    - name: Ensure gnupg is installed
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: yes

    - name: Create Wazuh repository file
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/wazuh.list
        line: 'deb https://packages.wazuh.com/4.x/apt stable main'
        create: yes
    
    - name: Activate Wazuh repository for updates
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/wazuh.list
        regexp: '^#deb https://packages.wazuh.com/4.x/apt stable main'
        line: 'deb https://packages.wazuh.com/4.x/apt stable main'
        state: present

    - name: Download Wazuh GPG key
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        dest: /tmp/GPG-KEY-WAZUH

    - name: Check if Wazuh GPG keyring already exists
      ansible.builtin.stat:
        path: /usr/share/keyrings/wazuh-archive-keyring.gpg
      register: wazuh_keyring

    - name: Convert Wazuh GPG key to keyring format
      ansible.builtin.command: "gpg --dearmor -o /usr/share/keyrings/wazuh-archive-keyring.gpg /tmp/GPG-KEY-WAZUH"
      become: true
      when: not wazuh_keyring.stat.exists
      timeout: 30

    - name: Add Wazuh repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/wazuh-archive-keyring.gpg] https://packages.wazuh.com/4.x/apt stable main'
        state: present
        filename: wazuh

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Wazuh Agent
      ansible.builtin.apt:
        name: wazuh-agent
        state: present

    - name: replace MANAGER_IP in ossec.conf
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>MANAGER_IP</address>'
        replace: '<address>PUTIPHERE</address>'

    - name: Stop Wazuh Agent
      ansible.builtin.systemd:
        name: wazuh-agent
        state: stopped

    - name: Enable wazuh-agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start Wazuh Agent
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started

    - name: Hold wazuh-agent package
      ansible.builtin.shell: "echo 'wazuh-agent hold' | dpkg --set-selections"

    - name: Update apt cache after hold on wazuh package
      ansible.builtin.apt:
        update_cache: yes
