---
- hosts: all
  vars:
    ansible_host_key_checking: false
  gather_facts: yes
  become: yes
  
  tasks:
  
  - name: install rsyslog
    apt:
      name:
        - rsyslog
      update_cache: yes
