---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_host_key_checking: false

  tasks:
    - name: reboot
      reboot:
        reboot_timeout: 120
        test_command: uptime
      ignore_errors: true
