---
- name: NTP Configuration
  hosts: all
  vars:
    ansible_host_key_checking: false
  become: true
  tasks:
    - name: create folder /var/log/ntpsec
      file:
        path: /var/log/ntpsec
        state: directory
        owner: root
        group: root
        mode: '0777'
      register: result_mkdir 
    - name: Update NTP configuration
      lineinfile:
        path: /etc/ntpsec/ntp.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'pool 0.debian.pool.ntp.org iburst', line: 'server de.pool.ntp.org iburst' }
        - { regexp: 'pool 1.debian.pool.ntp.org iburst', line: '#pool 2.debian.pool.ntp.org iburst' }
        - { regexp: 'pool 2.debian.pool.ntp.org iburst', line: '#pool 3.debian.pool.ntp.org iburst' }
        - { regexp: 'pool 3.debian.pool.ntp.org iburst', line: '#pool 4.debian.pool.ntp.org iburst' }
    - name: Restart NTP service
      service:
        name: ntp
        state: restarted
