---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_host_key_checking: false

  tasks:
    - name: apt update
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: apt dist-upgrade
      become: yes
      apt:
        upgrade: dist
        update_cache: yes

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server if required
      become: yes
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes
