---
- hosts: all
  vars:
    ansible_host_key_checking: false
  gather_facts: yes
  become: yes

  tasks:

    - name: Ensure Wazuh repository is correctly configured
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/wazuh.list
        state: absent  # Löscht die alte Datei, um sicherzustellen, dass es keine Fehler gibt

    - name: Create Wazuh repository file
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/wazuh.list
        line: 'deb https://packages.wazuh.com/4.x/apt stable main'
        create: yes
    
    - name: Activate Wazuh repository for updates
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/wazuh.list
        regexp: '^#deb https://packages.wazuh.com/4.x/apt stable main'
        line: 'deb https://packages.wazuh.com/4.x/apt stable main'
        state: present

    - name: Download Wazuh GPG key
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        dest: /tmp/GPG-KEY-WAZUH

    - name: Convert Wazuh GPG key to keyring format
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /usr/share/keyrings/wazuh-archive-keyring.gpg /tmp/GPG-KEY-WAZUH"

    - name: Add Wazuh repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/wazuh-archive-keyring.gpg] https://packages.wazuh.com/4.x/apt stable main'
        state: present
        filename: wazuh

    - name: uhold wazuh-agent package
      ansible.builtin.shell: "echo 'wazuh-agent install' | dpkg --set-selections"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade Wazuh agent package
      ansible.builtin.apt:
        name: wazuh-agent
        state: latest

    - name: Ensure wazuh-agent is enabled and running
      ansible.builtin.service:
        name: wazuh-agent
        state: started
        enabled: true

    - name: Hold wazuh-agent package
      ansible.builtin.shell: "echo 'wazuh-agent hold' | dpkg --set-selections"
